### ISSUE TITLE
categorial variables

### ISSUE THREAD

**Issue by misbahch6** [kundajelab/deeplift#115]
Hi,  
very nice work.

I would like to know how would you interpret contribution of categorical variables. 
My data is mixed, containing continuous and categorical features. 
I have 2 output neurons.
so if particular categorical variable has high score then how would you interpret it ? For example I have one variable family_history with values 0 and 1. Deeplift gives high importance score to this variable. So which category of this variable is important actually ? Having family history (1) or not having it (0). Hope my question is clear

thank you,

**Comment by AvantiShri** [comment]
Hi @misbahch6,

It would depend on three things:
(1) What was the reference a.k.a. baseline that you used?
(2) Which output task are you computing the importance with respect to?
(3) What is the sign of the importance that you observe for a particular example?

Say you used a baseline of all-zeros. Now consider an example where the family history is a 1. The difference-from-baseline for family history for this example is a +1 (because 1-0 = +1). Now let's say that when you compute the scores for output neuron 1, you observe positive importance for family history, whereas if you compute the scores for output neuron 2, you observe a negative importance for family history. This indicates that family history being "1" (rather than zero) contributes positively to output neuron 1, whereas it contributes negatively to output neuron 2. In all, this suggests that a family history of 1 is important for receiving a high score in output neuron 1, whereas a family history of 0 is important for receiving a high score in output neuron 2.

Does that make sense?

Best,
Avanti

**Comment by misbahch6** [comment]
thank you so much. it is super clear response 
:100:
