### ISSUE TITLE
Can we get all m_{xy} or C_{xy} values from the model for all layers?

### ISSUE THREAD

**Issue by younglululu** [kundajelab/deeplift#37]

**Comment by AvantiShri** [comment]
Hi younglululu,

I had to refresh my memory, but the answer is yes! find_scores_layer_idx (for a sequential model) and find_scores_layer_name (for a graph model) can actually be lists:

https://github.com/kundajelab/deeplift/blob/master/deeplift/models.py#L225-L227
https://github.com/kundajelab/deeplift/blob/master/deeplift/models.py#L278-L280

I would have changed the names of the arguments to reflect this, but I didn't want to break the API. Let me know if you have any issues.

**Comment by AvantiShri** [comment]
Oh, one more followup remark; for all layers except the input layer, multipliers are split up into pos_mxts and neg_mxts (as needed by the RevealCancel rule described in the DeepLIFT paper). For layers that act as inputs to nonlinearities, these will be different, but for layers that act as inputs to a linear layer, these should be the same. Because `get_mxts()` is not defined for anything other than Input layers (instead, there is `get_pos_mxts()` and `get_neg_mxts()`), you could modify the following line https://github.com/kundajelab/deeplift/blob/master/deeplift/models.py#L56 to use the average of `get_pos_mxts()` and `get_neg_mxts()` if `get_mxts()` is not defined for the layer. The code would look something like this:

```
output_symbolic_vars = [
             (find_scores_layer.get_mxts() if hasattr(find_scores_layer, 'get_mxts())
              else 0.5*(find_scores_layer.get_pos_mxts() + find_scores_layer.get_neg_mxts()))
             for find_scores_layer in find_scores_layers]
```
Let me know if that works for your purposes, and if it does, would be happy to accept a pull request to the main code base!
